
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import {Archivo} from "next/font/google"
import Provider from "./provider";

export const metadata = {
  title: "DriveScape",
  description: "Generated by create next app",
};

const outfit = Archivo({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
      className={outfit.className}
      >
        <Provider>
        {children}
        </Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
